server:
  port: 8082
spring:
  application:
    name: sale-service
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    zipkin:
      base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
eureka:
  instance:
    hostname: localhost
  client:
    defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG